module.exports = {
    "abilities": "Ability",
    "ammunition": "Ammunition",
    "armor_upgrades": "ArmorUpgrade",
    "armor": "Armor",
    "augmentations": "Augmentation",
    // "class_features": "ClassFeature",
    // "class_proficiencies": "ClassProficiency",
    // "class_special_skill_features": "ClassSpecialSkillFeature",
    // "class_special_skills": "ClassSpecialSkill",
    // "classes": "Class",
    // "companion_abilities": "CompanionAbility",
    "companions": "Companion",
    "drugs": "Drug",
    "effect_ranges": "EffectRange",
    "feats": "Feat",
    "goods_and_services": "GoodOrService",
    "items": "Item",
    "medicinals": "Medicinal",
    "poisons": "Poison",
    "powered_armor": "PoweredArmor",
    "races": "Race",
    "skills": "Skill",
    "solarian_crystals": "SolarianCrystal",
    "sources": "Source",
    // "spells": "Spell",
    "themes": "Theme",
    "vehicles": "Vehicle",
    "weapon_accessories": "WeaponAccessory",
    // "weapon_category": "WeaponCategory",
    "weapon_fusions": "WeaponFusion",
    "weapon_manufacturers": "WeaponManufacturer",
    "weapon_materials": "WeaponMaterials",
    "weapon_special_properties": "WeaponSpecialProperty",
    "weapons": "Weapon",
}