name: Update Sentry Releases

on:
    pull_request:
        branches: [ master ]

#   push:
#     tags:
#       - '*'
#     paths-ignore:
#     - 'docs/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 10

        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install requests

        - name: Get full git commit history
          run: git clone https://github.com/bocks-ds/sf-datasource.git
        - name: Make sentry release
          run: |
            cd .github/ && make release \
            TOKEN=${{ secrets.SENTRY_TOKEN }} \
            REPO_NAME=${{ secrets.REPO_NAME }} \
            OLDEST_COMMIT=${{ secrets.OLDEST_COMMIT }}
